// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: iherbCatalog.proto

package iherbCatalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IHerbCatalogService_GetProductData_FullMethodName = "/iherbCatalog.IHerbCatalogService/GetProductData"
)

// IHerbCatalogServiceClient is the client API for IHerbCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IHerbCatalogServiceClient interface {
	GetProductData(ctx context.Context, in *ProductDataRequest, opts ...grpc.CallOption) (*ProductDataResponse, error)
}

type iHerbCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIHerbCatalogServiceClient(cc grpc.ClientConnInterface) IHerbCatalogServiceClient {
	return &iHerbCatalogServiceClient{cc}
}

func (c *iHerbCatalogServiceClient) GetProductData(ctx context.Context, in *ProductDataRequest, opts ...grpc.CallOption) (*ProductDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductDataResponse)
	err := c.cc.Invoke(ctx, IHerbCatalogService_GetProductData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IHerbCatalogServiceServer is the server API for IHerbCatalogService service.
// All implementations must embed UnimplementedIHerbCatalogServiceServer
// for forward compatibility.
type IHerbCatalogServiceServer interface {
	GetProductData(context.Context, *ProductDataRequest) (*ProductDataResponse, error)
	mustEmbedUnimplementedIHerbCatalogServiceServer()
}

// UnimplementedIHerbCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIHerbCatalogServiceServer struct{}

func (UnimplementedIHerbCatalogServiceServer) GetProductData(context.Context, *ProductDataRequest) (*ProductDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductData not implemented")
}
func (UnimplementedIHerbCatalogServiceServer) mustEmbedUnimplementedIHerbCatalogServiceServer() {}
func (UnimplementedIHerbCatalogServiceServer) testEmbeddedByValue()                             {}

// UnsafeIHerbCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IHerbCatalogServiceServer will
// result in compilation errors.
type UnsafeIHerbCatalogServiceServer interface {
	mustEmbedUnimplementedIHerbCatalogServiceServer()
}

func RegisterIHerbCatalogServiceServer(s grpc.ServiceRegistrar, srv IHerbCatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedIHerbCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IHerbCatalogService_ServiceDesc, srv)
}

func _IHerbCatalogService_GetProductData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IHerbCatalogServiceServer).GetProductData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IHerbCatalogService_GetProductData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IHerbCatalogServiceServer).GetProductData(ctx, req.(*ProductDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IHerbCatalogService_ServiceDesc is the grpc.ServiceDesc for IHerbCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IHerbCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iherbCatalog.IHerbCatalogService",
	HandlerType: (*IHerbCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductData",
			Handler:    _IHerbCatalogService_GetProductData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iherbCatalog.proto",
}
