// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: iherbCatalog.proto

package iherbCatalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockStatusEnum int32

const (
	StockStatusEnum_UndefinedStatus StockStatusEnum = 0
	StockStatusEnum_InStock         StockStatusEnum = 1
	StockStatusEnum_OutOfStock      StockStatusEnum = 2
)

// Enum value maps for StockStatusEnum.
var (
	StockStatusEnum_name = map[int32]string{
		0: "UndefinedStatus",
		1: "InStock",
		2: "OutOfStock",
	}
	StockStatusEnum_value = map[string]int32{
		"UndefinedStatus": 0,
		"InStock":         1,
		"OutOfStock":      2,
	}
)

func (x StockStatusEnum) Enum() *StockStatusEnum {
	p := new(StockStatusEnum)
	*p = x
	return p
}

func (x StockStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StockStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_iherbCatalog_proto_enumTypes[0].Descriptor()
}

func (StockStatusEnum) Type() protoreflect.EnumType {
	return &file_iherbCatalog_proto_enumTypes[0]
}

func (x StockStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StockStatusEnum.Descriptor instead.
func (StockStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_iherbCatalog_proto_rawDescGZIP(), []int{0}
}

type ProductDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDataRequest) Reset() {
	*x = ProductDataRequest{}
	mi := &file_iherbCatalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDataRequest) ProtoMessage() {}

func (x *ProductDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iherbCatalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDataRequest.ProtoReflect.Descriptor instead.
func (*ProductDataRequest) Descriptor() ([]byte, []int) {
	return file_iherbCatalog_proto_rawDescGZIP(), []int{0}
}

func (x *ProductDataRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductDataResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BasePrice          float32                `protobuf:"fixed32,2,opt,name=BasePrice,proto3" json:"BasePrice,omitempty"`
	BasePriceFormatted string                 `protobuf:"bytes,3,opt,name=BasePriceFormatted,proto3" json:"BasePriceFormatted,omitempty"`
	StockStatus        StockStatusEnum        `protobuf:"varint,4,opt,name=StockStatus,proto3,enum=iherbCatalog.StockStatusEnum" json:"StockStatus,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProductDataResponse) Reset() {
	*x = ProductDataResponse{}
	mi := &file_iherbCatalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDataResponse) ProtoMessage() {}

func (x *ProductDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iherbCatalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDataResponse.ProtoReflect.Descriptor instead.
func (*ProductDataResponse) Descriptor() ([]byte, []int) {
	return file_iherbCatalog_proto_rawDescGZIP(), []int{1}
}

func (x *ProductDataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDataResponse) GetBasePrice() float32 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *ProductDataResponse) GetBasePriceFormatted() string {
	if x != nil {
		return x.BasePriceFormatted
	}
	return ""
}

func (x *ProductDataResponse) GetStockStatus() StockStatusEnum {
	if x != nil {
		return x.StockStatus
	}
	return StockStatusEnum_UndefinedStatus
}

var File_iherbCatalog_proto protoreflect.FileDescriptor

const file_iherbCatalog_proto_rawDesc = "" +
	"\n" +
	"\x12iherbCatalog.proto\x12\fiherbCatalog\"2\n" +
	"\x12ProductDataRequest\x12\x1c\n" +
	"\tProductId\x18\x01 \x01(\rR\tProductId\"\xb8\x01\n" +
	"\x13ProductDataResponse\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tBasePrice\x18\x02 \x01(\x02R\tBasePrice\x12.\n" +
	"\x12BasePriceFormatted\x18\x03 \x01(\tR\x12BasePriceFormatted\x12?\n" +
	"\vStockStatus\x18\x04 \x01(\x0e2\x1d.iherbCatalog.StockStatusEnumR\vStockStatus*C\n" +
	"\x0fStockStatusEnum\x12\x13\n" +
	"\x0fUndefinedStatus\x10\x00\x12\v\n" +
	"\aInStock\x10\x01\x12\x0e\n" +
	"\n" +
	"OutOfStock\x10\x022n\n" +
	"\x13IHerbCatalogService\x12W\n" +
	"\x0eGetProductData\x12 .iherbCatalog.ProductDataRequest\x1a!.iherbCatalog.ProductDataResponse\"\x00B:Z8github.com/zakharova-e/iherb-scraper-server/iherbCatalogb\x06proto3"

var (
	file_iherbCatalog_proto_rawDescOnce sync.Once
	file_iherbCatalog_proto_rawDescData []byte
)

func file_iherbCatalog_proto_rawDescGZIP() []byte {
	file_iherbCatalog_proto_rawDescOnce.Do(func() {
		file_iherbCatalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iherbCatalog_proto_rawDesc), len(file_iherbCatalog_proto_rawDesc)))
	})
	return file_iherbCatalog_proto_rawDescData
}

var file_iherbCatalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iherbCatalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_iherbCatalog_proto_goTypes = []any{
	(StockStatusEnum)(0),        // 0: iherbCatalog.StockStatusEnum
	(*ProductDataRequest)(nil),  // 1: iherbCatalog.ProductDataRequest
	(*ProductDataResponse)(nil), // 2: iherbCatalog.ProductDataResponse
}
var file_iherbCatalog_proto_depIdxs = []int32{
	0, // 0: iherbCatalog.ProductDataResponse.StockStatus:type_name -> iherbCatalog.StockStatusEnum
	1, // 1: iherbCatalog.IHerbCatalogService.GetProductData:input_type -> iherbCatalog.ProductDataRequest
	2, // 2: iherbCatalog.IHerbCatalogService.GetProductData:output_type -> iherbCatalog.ProductDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_iherbCatalog_proto_init() }
func file_iherbCatalog_proto_init() {
	if File_iherbCatalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iherbCatalog_proto_rawDesc), len(file_iherbCatalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iherbCatalog_proto_goTypes,
		DependencyIndexes: file_iherbCatalog_proto_depIdxs,
		EnumInfos:         file_iherbCatalog_proto_enumTypes,
		MessageInfos:      file_iherbCatalog_proto_msgTypes,
	}.Build()
	File_iherbCatalog_proto = out.File
	file_iherbCatalog_proto_goTypes = nil
	file_iherbCatalog_proto_depIdxs = nil
}
