package models

type ProductData struct {
	CanonicalPaths [][]struct {
		DisplayName string `json:"displayName"`
		URL         string `json:"url"`
	} `json:"canonicalPaths"`
	BrandName            string        `json:"brandName"`
	BrandURL             string        `json:"brandUrl"`
	BrandCode            string        `json:"brandCode"`
	BrandManufacturerURL string        `json:"brandManufacturerUrl"`
	DisplayName          string        `json:"displayName"`
	Flag                 []interface{} `json:"flag"`
	PrimaryImageIndex    int           `json:"primaryImageIndex"`
	PartNumber           string        `json:"partNumber"`
	ImageIndices         []int         `json:"imageIndices"`
	CampaignImages       []string      `json:"campaignImages"`
	ImageIndices360      []int         `json:"imageIndices360"`
	RetailPrice          string        `json:"retailPrice"`
	ListPrice            string        `json:"listPrice"`
	ListPriceAmount      float32       `json:"listPriceAmount"`
	DiscountPrice        string        `json:"discountPrice"`
	DiscountAmt          string        `json:"discountAmt"`
	DiscountPriceAmount  float32       `json:"discountPriceAmount"`
	PricePerUnit         string        `json:"pricePerUnit"`
	ListPricePerUnit     string        `json:"listPricePerUnit"`
	DiscountPricePerUnit string        `json:"discountPricePerUnit"`
	ListPricePerUnits    struct {
		Imperial string `json:"imperial"`
		Metric   string `json:"metric"`
	} `json:"listPricePerUnits"`
	PricePerUnits struct {
		Imperial string `json:"imperial"`
		Metric   string `json:"metric"`
	} `json:"pricePerUnits"`
	StockStatus                       int         `json:"stockStatus"`
	StockStatusV2                     int         `json:"stockStatusV2"`
	StockStatusMessage                string      `json:"stockStatusMessage"`
	HasBackInStockDate                bool        `json:"hasBackInStockDate"`
	BackInStockDate                   interface{} `json:"backInStockDate"`
	FormattedComingSoonDate           interface{} `json:"formattedComingSoonDate"`
	BackInStockDateUnavailableMessage string      `json:"backInStockDateUnavailableMessage"`
	ExpirationDate                    string      `json:"expirationDate"`
	FormattedExpirationDate           string      `json:"formattedExpirationDate"`
	Weight                            string      `json:"weight"`
	PackageQuantity                   string      `json:"packageQuantity"`
	PackageQuantities                 struct {
		Imperial string `json:"imperial"`
		Metric   string `json:"metric"`
	} `json:"packageQuantities"`
	Dimensions                            string        `json:"dimensions"`
	ActualWeight                          string        `json:"actualWeight"`
	Description                           string        `json:"description"`
	Ingredients                           string        `json:"ingredients"`
	SpecialNote                           string        `json:"specialNote"`
	SuggestedUse                          string        `json:"suggestedUse"`
	SupplementFacts                       string        `json:"supplementFacts"`
	Warnings                              string        `json:"warnings"`
	IsAvailableToPurchase                 bool          `json:"isAvailableToPurchase"`
	URLName                               string        `json:"urlName"`
	ID                                    int           `json:"id"`
	URL                                   string        `json:"url"`
	ProductStatus                         int           `json:"productStatus"`
	IsDiscontinued                        bool          `json:"isDiscontinued"`
	IsComingSoon                          bool          `json:"isComingSoon"`
	QtyLimit                              int           `json:"qtyLimit"`
	QuantityLimit                         int           `json:"quantityLimit"`
	AutoShipQuantityLimit                 int           `json:"autoShipQuantityLimit"`
	SpecialDealInfo                       interface{}   `json:"specialDealInfo"`
	TrialDiscountInfo                     interface{}   `json:"trialDiscountInfo"`
	DiscountType                          int           `json:"discountType"`
	DiscountDisplayType                   int           `json:"discountDisplayType"`
	IsInCartDiscount                      bool          `json:"isInCartDiscount"`
	SalesDiscountPercentage               float64       `json:"salesDiscountPercentage"`
	RootCategoryID                        int           `json:"rootCategoryId"`
	RootCategoryName                      string        `json:"rootCategoryName"`
	EnRootCategoryName                    string        `json:"enRootCategoryName"`
	FormattedOnSaleDate                   string        `json:"formattedOnSaleDate"`
	WeightLb                              string        `json:"weightLb"`
	WeightKg                              string        `json:"weightKg"`
	DimensionsIn                          string        `json:"dimensionsIn"`
	DimensionsCm                          string        `json:"dimensionsCm"`
	HasExpirationDate                     bool          `json:"hasExpirationDate"`
	ManufacturerAddresses                 []interface{} `json:"manufacturerAddresses"`
	EnabledDiscountBanner                 bool          `json:"enabledDiscountBanner"`
	EnabledDiscountForPreviouslyPurchased bool          `json:"enabledDiscountForPreviouslyPurchased"`
	RestrictedCountries                   []interface{} `json:"restrictedCountries"`
	LegalNotice                           string        `json:"legalNotice"`
	RecentActivityMessage                 string        `json:"recentActivityMessage"`
	RecentActivityCount                   int           `json:"recentActivityCount"`
	Prohibited                            bool          `json:"prohibited"`
	CustomerVisible                       bool          `json:"customerVisible"`
	InStockInExcludedWarehouses           bool          `json:"inStockInExcludedWarehouses"`
	IsWeightManagementProduct             bool          `json:"isWeightManagementProduct"`
}
